### ISSUE TITLE
1.0.7 yanked from ruby gems

### ISSUE THREAD

**Issue by PWKad** [BlockIo/gem-block-io#2]
https://rubygems.org/gems/block_io/versions/1.0.7

Version 1.0.7 has security updates but has been yanked.  Does this mean the ruby gem will no longer be supported?

**Comment by doersf** [comment]
Hi, the push was determined to not work with some versions of included due to the TLSv1_2 symbol. This will get updated as 1.0.8.

**Comment by PWKad** [comment]
Thanks for the response, given the name of the release for 1.0.7 was `Security Update` does this mean that one should suspend use of the gem until 1.0.8 is released or 1.0.6 is stable enough for consumption?

**Comment by doersf** [comment]
Hi, you can keep using the gem without issue. The only issue with it was the TLSv1_2 symbol not working on some platforms. If it works for you, it's just fine.

**Comment by PWKad** [comment]
Sounds good, I'll close this issue but by yanking off of ruby gems the gem is very difficult to use because CI environments can't find it.

**Comment by doersf** [comment]
Acknowledged.
