### ISSUE TITLE
Intermittent SSL issues "SSL_read: decryption failed or bad record mac"

### ISSUE THREAD

**Issue by PWKad** [BlockIo/gem-block-io#3]
I'm intermittently receiving this error on 1.0.8 -

![image](https://user-images.githubusercontent.com/4238393/31751727-a062dc7c-b44c-11e7-99fe-e3bfffec3b69.png)

Any ideas?  Appears to be originating on the block.io side.

**Comment by doersf** [comment]
This is a network connectivity issue where you're not receiving the full body of the response.
